import { getTier, type TierName } from './handicap';
import type { Player } from './types';

// Current HC rankings were provided manually by the app owner from the CueScore
// Biljardna zveza Slovenije handicap dashboard on 2026-06-03. The dashboard URL
// may require a signed-in session, so these rows are kept as editable seed data.
export const currentHandicapRows: Array<{ name: string; tier: TierName }> = [
  { name: 'Adnan Bašić', tier: 'B2' },
  { name: 'Aleksander Mavric', tier: 'B1' },
  { name: 'Aleksander Raišič', tier: 'A2' },
  { name: 'Aleš Kokalj', tier: 'A3' },
  { name: 'Aleš Mandič', tier: 'A1' },
  { name: 'Alex Grigolunovich', tier: 'A3' },
  { name: 'Ali Arszlan', tier: 'A3' },
  { name: 'Ana Gradisnik', tier: 'A+' },
  { name: 'Anastasia Losseva', tier: 'B2' },
  { name: 'Andrej Hribljan', tier: 'B2' },
  { name: 'Andrej Uglešić', tier: 'B1' },
  { name: 'Andrejs Grigolunovičs', tier: 'B2' },
  { name: 'Anže Ciuha', tier: 'B1' },
  { name: 'Armen Bdoian', tier: 'B1' },
  { name: 'Arzslan Ali', tier: 'A3' },
  { name: 'Ąžuolas Tadaravičius', tier: 'A+' },
  { name: 'Blaz Kolenc', tier: 'A1' },
  { name: 'Blaž Rauter', tier: 'A3' },
  { name: 'Blaž Resnik', tier: 'A1' },
  { name: 'Blaž Rus', tier: 'A2' },
  { name: 'Blaž Vrankar', tier: 'B2' },
  { name: 'Blendi Ukimeri', tier: 'B2' },
  { name: 'Bojan Uljan', tier: 'A2' },
  { name: 'Boris Doberšek', tier: 'B1' },
  { name: 'Boris Erculj', tier: 'A+' },
  { name: 'Borys Gaćkowski', tier: 'A1' },
  { name: 'Boštjan Božič', tier: 'B1' },
  { name: 'Boštjan Marolt', tier: 'B1' },
  { name: 'Dalibor Drljača', tier: 'B1' },
  { name: 'Damir Petrinec', tier: 'A3' },
  { name: 'Damjan Kraševec', tier: 'A3' },
  { name: 'Darko Filipovic', tier: 'B1' },
  { name: 'David Benedicic', tier: 'B2' },
  { name: 'David Gradišnik', tier: 'B1' },
  { name: 'David Rus', tier: 'B2' },
  { name: 'Davide Bussani', tier: 'A3' },
  { name: 'Davor Polak', tier: 'A3' },
  { name: 'Dejan Dim', tier: 'B2' },
  { name: 'Dejan Simič', tier: 'A3' },
  { name: 'Denis Jasnič', tier: 'A3' },
  { name: 'Dino Nadarević', tier: 'A3' },
  { name: 'Domen Drol', tier: 'B3' },
  { name: 'Dominik Fendre', tier: 'B2' },
  { name: 'Dominik Steržaj', tier: 'B1' },
  { name: 'Dragan Spasovski', tier: 'B1' },
  { name: 'Dragan Spasovski', tier: 'B2' },
  { name: 'Drazen Vrhovac', tier: 'A1' },
  { name: 'Florijan Rostohar', tier: 'B1' },
  { name: 'Franc Srnec', tier: 'B2' },
  { name: 'Francesca Garlatti', tier: 'A3' },
  { name: 'Francesca Garlatti', tier: 'A3' },
  { name: 'Franci Čučnik', tier: 'A2' },
  { name: 'Gaja Rutar Doroslovac', tier: 'B-' },
  { name: 'Gašper Butina', tier: 'A3' },
  { name: 'Goran Delic', tier: 'A2' },
  { name: 'Goran Starčev', tier: 'B1' },
  { name: 'Goran Sztarcsev', tier: 'B1' },
  { name: 'Gorazd Žužek', tier: 'A3' },
  { name: 'Ilya Smirnov', tier: 'B1' },
  { name: 'Ivan Josič', tier: 'B1' },
  { name: 'Ivan Kretov', tier: 'A3' },
  { name: 'Iztok Mavsar', tier: 'A3' },
  { name: 'Jaka Gradišar', tier: 'B1' },
  { name: 'Jaka Korenčan', tier: 'B1' },
  { name: 'Jakob Humer', tier: 'B2' },
  { name: 'Jan Hvalec', tier: 'B1' },
  { name: 'Jan Slejko Ljubišič', tier: 'A2' },
  { name: 'Jan Slejko Ljubišič', tier: 'A2' },
  { name: 'Janez Lavrič', tier: 'B1' },
  { name: 'Janez Pavlovič', tier: 'A2' },
  { name: 'Janez Rajnar', tier: 'B1' },
  { name: 'Janez Rajnar', tier: 'B1' },
  { name: 'Janko Kočar', tier: 'B1' },
  { name: 'Jasmin Čaušević', tier: 'A2' },
  { name: 'Jelizaveta Dzebisašvili', tier: 'B2' },
  { name: 'Jelka Kelec', tier: 'B-' },
  { name: 'Jokubas Silantjevas', tier: 'A+' },
  { name: 'Jon Jelen', tier: 'A3' },
  { name: 'Jordan L', tier: 'B-' },
  { name: 'Joško Kuhelj', tier: 'B1' },
  { name: 'Jože Marinko', tier: 'A2' },
  { name: 'Jure Dobrajc', tier: 'B2' },
  { name: 'Jure dobrajc', tier: 'B2' },
  { name: 'Kęstutis Žadeikis', tier: 'Pro' },
  { name: 'Klavdij Ferle', tier: 'A3' },
  { name: 'Klemen Gradišnik', tier: 'A+' },
  { name: 'Klemen Šorak', tier: 'A3' },
  { name: 'Klemen Sorak', tier: 'A3' },
  { name: 'Kristijan Nikl', tier: 'A3' },
  { name: 'Lan Mrovlje', tier: 'A3' },
  { name: 'Lazar Olić', tier: 'B1' },
  { name: 'Lovro Bračun', tier: 'A1' },
  { name: 'Lovro Kokot', tier: 'A3' },
  { name: 'Luka Drljača', tier: 'A3' },
  { name: 'Magic Wladimir', tier: 'B1' },
  { name: 'Maj Badovinac', tier: 'A+' },
  { name: 'Maja Globočnik', tier: 'A2' },
  { name: 'Maks Benko', tier: 'Pro' },
  { name: 'Maksim Doberšek', tier: 'B1' },
  { name: 'Manuel Ghiro', tier: 'B1' },
  { name: 'Marcel Žibret', tier: 'B2' },
  { name: 'Marijan Bratić', tier: 'B1' },
  { name: 'Marjan Lesar', tier: 'B1' },
  { name: 'Mark Lakner', tier: 'B3' },
  { name: 'Mark Metelko', tier: 'B1' },
  { name: 'Marko Avramovic', tier: 'A3' },
  { name: 'Marko Hočevar', tier: 'B1' },
  { name: 'Marko Podgoršek', tier: 'B1' },
  { name: 'Martin Lampret', tier: 'B1' },
  { name: 'Matej Brajkovič', tier: 'A2' },
  { name: 'Matej Dakol', tier: 'A2' },
  { name: 'Matej Kovac', tier: 'A2' },
  { name: 'Matej Michler', tier: 'B2' },
  { name: 'Matic Kunstelj', tier: 'B1' },
  { name: 'Matic Rudolf', tier: 'A3' },
  { name: 'Matjaž Demšar', tier: 'A2' },
  { name: 'Matjaž Erčulj', tier: 'A+' },
  { name: 'Matjaž Kastelic', tier: 'B2' },
  { name: 'Matjaž Košar', tier: 'A2' },
  { name: 'Matjaz Kozamernik', tier: 'A2' },
  { name: 'Miha Papler', tier: 'B1' },
  { name: 'Miha Plut', tier: 'B1' },
  { name: 'Miha Ribaric', tier: 'B2' },
  { name: 'Miha Skerlavaj', tier: 'A1' },
  { name: 'Miha Vičič Šnajdar', tier: 'A+' },
  { name: 'Miha Zajc Zaytsev', tier: 'A1' },
  { name: 'Mirnes Mahmutovic', tier: 'B1' },
  { name: 'Mitja Gradišnik', tier: 'A+' },
  { name: 'Mitja Kragelj', tier: 'A3' },
  { name: 'Mitja Svoljšak', tier: 'B1' },
  { name: 'Natalija Golob', tier: 'A2' },
  { name: 'Nik Rus', tier: 'A3' },
  { name: 'Nikita Marojević', tier: 'A1' },
  { name: 'Nikola Lukašikas', tier: 'A2' },
  { name: 'Obid Boštjan', tier: 'A2' },
  { name: 'Oleg Birgmajer', tier: 'B1' },
  { name: 'Olexandr Rozumovsky', tier: 'B1' },
  { name: 'Peter Drame', tier: 'A3' },
  { name: 'Philip Jokic', tier: 'B1' },
  { name: 'Rado Doroslovac', tier: 'A1' },
  { name: 'Radulovic Zoran', tier: 'B1' },
  { name: 'Robert Rednak', tier: 'A2' },
  { name: 'Roberto Bartol', tier: 'Pro' },
  { name: 'Rok Količ', tier: 'B1' },
  { name: 'Rok Spindler', tier: 'B1' },
  { name: 'Samir Mahmutovic', tier: 'A3' },
  { name: 'Sebastjan Dolamic', tier: 'B1' },
  { name: 'Seif eddine Boucheligua', tier: 'A1' },
  { name: 'simon bartolj', tier: 'B1' },
  { name: 'Simon Tomažič', tier: 'A1' },
  { name: 'Srdja Vukajlovic', tier: 'A2' },
  { name: 'Stane Jelačin', tier: 'B2' },
  { name: 'Svit Pavlinjek', tier: 'A1' },
  { name: 'Szymon Porczyk', tier: 'B3' },
  { name: 'Tadej Raisic', tier: 'B-' },
  { name: 'Tilen Gombač', tier: 'B3' },
  { name: 'Tim Ursic', tier: 'B2' },
  { name: 'Timotej Dundovic', tier: 'B2' },
  { name: 'Tina Zdešar Kolenc', tier: 'B3' },
  { name: 'Tomaž Benedičič', tier: 'B1' },
  { name: 'Tomaz Varvaris', tier: 'B1' },
  { name: 'Tomi Bratina', tier: 'A3' },
  { name: 'Tomo Blaževič', tier: 'B2' },
  { name: 'Tristan Šulek', tier: 'A1' },
  { name: 'Vanja Raisic', tier: 'B-' },
  { name: 'Vid Kuklec', tier: 'B1' },
  { name: 'Vladimir Mikek', tier: 'B1' },
  { name: 'Vuk Strugar', tier: 'A1' },
  { name: 'Ziga Kovac', tier: 'A3' },
];

function slugify(value: string) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export const seedPlayers: Player[] = currentHandicapRows.map((row, index) => ({
  id: `${slugify(row.name) || 'player'}-${index + 1}`,
  name: row.name,
  visibleTier: row.tier,
  sourceHandicap: row.tier,
  minimumTier: row.tier,
  backgroundElo: getTier(row.tier).baselineElo,
  tournamentPoints: 0,
}));
